version: '3'
services:
    mongodb:
        image: mongo:4
        logging: 
            driver: "none"
        ports:
            - 27017:27017
    
    backend:
        build: backend
        command:  npm start
        ports: 
            - 3600:3600
        restart:
            always
        environment:
            URL: mongodb
            PORT: 3600
            SECRET: "SONICBOLT123"
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./src/backend
            - nodemodules:/backend/node_modules
        links:
            - mongodb
        depends_on:
            - mongodb
    frontend: 
        build: frontend
        command: npm start
        ports:
            - 3000:3000
        environment:
            REACT_APP_BACKEND: http://localhost:3600/api
            REACT_APP_SECRET: "SONICBOLT123"
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./src/frontend
            - nodemodules:/frontend/node_modules
        depends_on:
            - backend
volumes:
    nodemodules: {}